# -*- mode: makefile-gmake; coding:utf-8 -*-
#
#  Yet Another Teachable Operating System
#  Copyright 2016 Takeharu KATO
#
top=../..
include ${top}/mk/Makefile.inc

all: distclean

clean:

distclean:
	$(call dist-clean-objs)
