# -*- mode: makefile-gmake; coding:utf-8 -*-
# OS kernel sample
# Copyright 2019 Takeharu KATO
#
top=../..
include ${top}/Makefile.inc

all: distclean

clean:
	${RM} ${CLEAN_FILES} asm-offset.h

distclean: clean
	${RM} ${DIST_CLEAN_FILES}
